In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [29]:
df=pd.read_csv('crime.csv')

In [30]:
df

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y,Latitude,Longitude
0,Other Theft,2003,5,12,16.0,15.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
1,Other Theft,2003,5,7,15.0,20.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
2,Other Theft,2003,4,23,16.0,40.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
3,Other Theft,2003,4,20,11.0,15.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
4,Other Theft,2003,4,12,17.0,45.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
...,...,...,...,...,...,...,...,...,...,...,...,...
530647,Break and Enter Residential/Other,2017,3,3,9.0,16.0,31XX ADANAC ST,Hastings-Sunrise,497265.49,5458296.71,49.277420,-123.037595
530648,Mischief,2017,5,29,22.0,30.0,14XX E 7TH AVE,Grandview-Woodland,494533.97,5456824.97,49.264163,-123.075129
530649,Offence Against a Person,2017,4,13,NaN,NaN,OFFSET TO PROTECT PRIVACY,NaN,0.00,0.00,0.000000,0.000000
530650,Theft from Vehicle,2017,6,5,17.0,0.0,8XX HAMILTON ST,Central Business District,491487.85,5458385.78,49.278168,-123.117031
530651,Vehicle Collision or Pedestrian Struck (with I...,2017,6,6,17.0,38.0,13XX BLOCK PARK DR,Marpole,490204.00,5451444.00,49.215706,-123.134512

In [31]:
df.dropna()

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y,Latitude,Longitude
0,Other Theft,2003,5,12,16.0,15.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
1,Other Theft,2003,5,7,15.0,20.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
2,Other Theft,2003,4,23,16.0,40.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
3,Other Theft,2003,4,20,11.0,15.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
4,Other Theft,2003,4,12,17.0,45.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763
...,...,...,...,...,...,...,...,...,...,...,...,...
530646,Mischief,2017,1,18,14.0,44.0,14XX E HASTINGS ST,Grandview-Woodland,494563.75,5458727.40,49.281276,-123.074746
530647,Break and Enter Residential/Other,2017,3,3,9.0,16.0,31XX ADANAC ST,Hastings-Sunrise,497265.49,5458296.71,49.277420,-123.037595
530648,Mischief,2017,5,29,22.0,30.0,14XX E 7TH AVE,Grandview-Woodland,494533.97,5456824.97,49.264163,-123.075129
530650,Theft from Vehicle,2017,6,5,17.0,0.0,8XX HAMILTON ST,Central Business District,491487.85,5458385.78,49.278168,-123.117031
530651,Vehicle Collision or Pedestrian Struck (with I...,2017,6,6,17.0,38.0,13XX BLOCK PARK DR,Marpole,490204.00,5451444.00,49.215706,-123.134512

In [34]:
encoder = OneHotEncoder()


encoded_data = encoder.fit_transform(df[['NEIGHBOURHOOD']])


df_encoded = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['NEIGHBOURHOOD']))

df_encoded

,NEIGHBOURHOOD_Arbutus Ridge,NEIGHBOURHOOD_Central Business District,NEIGHBOURHOOD_Dunbar-Southlands,NEIGHBOURHOOD_Fairview,NEIGHBOURHOOD_Grandview-Woodland,NEIGHBOURHOOD_Hastings-Sunrise,NEIGHBOURHOOD_Kensington-Cedar Cottage,NEIGHBOURHOOD_Kerrisdale,NEIGHBOURHOOD_Killarney,NEIGHBOURHOOD_Kitsilano,...,NEIGHBOURHOOD_Riley Park,NEIGHBOURHOOD_Shaughnessy,NEIGHBOURHOOD_South Cambie,NEIGHBOURHOOD_Stanley Park,NEIGHBOURHOOD_Strathcona,NEIGHBOURHOOD_Sunset,NEIGHBOURHOOD_Victoria-Fraserview,NEIGHBOURHOOD_West End,NEIGHBOURHOOD_West Point Grey,NEIGHBOURHOOD_nan
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530647,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530648,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530649,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
530650,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
encoder = OneHotEncoder()


encoded_data = encoder.fit_transform(df[['NEIGHBOURHOOD']])


df_encoded = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['NEIGHBOURHOOD']))


df_encoded

,NEIGHBOURHOOD_Arbutus Ridge,NEIGHBOURHOOD_Central Business District,NEIGHBOURHOOD_Dunbar-Southlands,NEIGHBOURHOOD_Fairview,NEIGHBOURHOOD_Grandview-Woodland,NEIGHBOURHOOD_Hastings-Sunrise,NEIGHBOURHOOD_Kensington-Cedar Cottage,NEIGHBOURHOOD_Kerrisdale,NEIGHBOURHOOD_Killarney,NEIGHBOURHOOD_Kitsilano,...,NEIGHBOURHOOD_Riley Park,NEIGHBOURHOOD_Shaughnessy,NEIGHBOURHOOD_South Cambie,NEIGHBOURHOOD_Stanley Park,NEIGHBOURHOOD_Strathcona,NEIGHBOURHOOD_Sunset,NEIGHBOURHOOD_Victoria-Fraserview,NEIGHBOURHOOD_West End,NEIGHBOURHOOD_West Point Grey,NEIGHBOURHOOD_nan
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530647,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530648,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530649,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
530650,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
530651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
scaler = MinMaxScaler()

df_normalize = df[['MONTH','DAY','HOUR','MINUTE','Latitude','Longitude']]

In [40]:
df_normalized=scaler.fit_transform(df_normalize)

In [48]:
df_normalized_dataframe = pd.DataFrame(df_normalized,columns=df_normalize.columns)

In [49]:
df_normalized_dataframe

           MONTH       DAY      HOUR    MINUTE  Latitude  Longitude
0       0.363636  0.366667  0.695652  0.254237  0.990242   0.011770
1       0.363636  0.200000  0.652174  0.338983  0.990242   0.011770
2       0.272727  0.733333  0.695652  0.677966  0.990242   0.011770
3       0.272727  0.633333  0.478261  0.254237  0.990242   0.011770
4       0.272727  0.366667  0.739130  0.762712  0.990242   0.011770
...          ...       ...       ...       ...       ...        ...
530647  0.181818  0.066667  0.391304  0.271186  0.990395   0.012141
530648  0.363636  0.933333  0.956522  0.508475  0.990129   0.011840
530649  0.272727  0.400000       NaN       NaN  0.000000   1.000000
530650  0.454545  0.133333  0.739130  0.000000  0.990410   0.011503
530651  0.454545  0.166667  0.739130  0.644068  0.989155   0.011363

[530652 rows x 6 columns]

In [ ]:
max_longitude=